
SELECT * FROM zespoly
ORDER BY id_zesp

SELECT * FROM pracownicy
ORDER BY id_prac;

SELECT NAZWISKO, 12*PLACA_POD AS ROCZNA_PLACA FROM PRACOWNICY
ORDER BY NAZWISKO;

SELECT NAZWISKO, ETAT, PLACA_POD + COALESCE(PLACA_DOD, 0) AS MIESIECZNE_ZAROBKI FROM pracownicy
ORDER BY MIESIECZNE_ZAROBKI DESC;

SELECT * FROM zespoly
ORDER BY nazwa;

SELECT UNIQUE ETAT FROM pracownicy
ORDER BY ETAT;

SELECT * FROM pracownicy
WHERE etat = 'ASYSTENT'
ORDER BY nazwisko;

SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD, ID_ZESP FROM pracownicy
WHERE ID_ZESP = 30 OR ID_ZESP = 40
ORDER BY PLACA_POD DESC;

SELECT NAZWISKO, ID_ZESP, PLACA_POD FROM PRACOWNICY
WHERE placa_pod BETWEEN 300 AND 800
ORDER BY NAZWISKO;

SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY
WHERE NAZWISKO LIKE '%SKI'
ORDER BY nazwisko;

SELECT ID_PRAC, ID_SZEFA, NAZWISKO, PLACA_POD FROM PRACOWNICY
WHERE PLACA_POD > 1000 AND id_szefa IS NOT NULL;

SELECT NAZWISKO, ID_ZESP FROM PRACOWNICY
WHERE id_zesp = 20 AND (NAZWISKO LIKE 'M%' OR NAZWISKO LIKE '%SKI')
ORDER BY NAZWISKO;

SELECT NAZWISKO, ETAT, PLACA_POD/160 AS STAWKA FROM PRACOWNICY
WHERE ETAT != 'ADIUNKT' AND ETAT != 'ASYSTENT' AND ETAT != 'STAZYSTA' AND PLACA_POD NOT BETWEEN 400 AND 800
ORDER BY STAWKA;

SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_DOD FROM PRACOWNICY
WHERE PLACA_POD + COALESCE(PLACA_DOD, 0) > 1000
ORDER BY ETAT, NAZWISKO;

SELECT NAZWISKO || ' PRACUJE OD ' || ZATRUDNIONY || ' I ZARABIA ' || PLACA_POD AS PROFESOROWIE FROM PRACOWNICY
WHERE ETAT = 'PROFESOR'
ORDER BY PLACA_POD DESC;