SELECT nazwisko, SUBSTR(etat, 1, 2) || id_prac AS kod FROM PRACOWNICY;

SELECT NAZWISKO, TRANSLATE(NAZWISKO, 'KLM', 'XXX') AS wojna_literom FROM PRACOWNICY;

SELECT NAZWISKO FROM PRACOWNICY
WHERE SUBSTR(NAZWISKO, 1, LENGTH(NAZWISKO) / 2) LIKE '%L%';

SELECT NAZWISKO, ROUND(PLACA_POD * 1.15, 0) FROM PRACOWNICY;

SELECT NAZWISKO,
    PLACA_POD, 0.2 * PLACA_POD AS INWESTYCJA,
    (PLACA_POD * 0.2) * POWER(1 + 10/100, 10) AS KAPITAL, 
    (PLACA_POD * 0.2) * POWER(1 + 10/100, 10) - 0.2 * PLACA_POD AS ZYSK FROM PRACOWNICY;

SELECT NAZWISKO, ZATRUDNIONY, EXTRACT(year FROM (DATE '2000-01-01' - ZATRUDNIONY) YEAR TO MONTH) AS staz_w_2000r FROM PRACOWNICY;

SELECT NAZWISKO, TO_CHAR(ZATRUDNIONY, 'MONTH, DD YYYY') FROM PRACOWNICY
    WHERE ID_ZESP = 20;

SELECT NAZWA, ADRES,
    CASE
        WHEN ADRES LIKE 'PIOTROWO%' THEN 'NOWE MIASTO'
        WHEN ADRES LIKE 'WLODKOWICA%' THEN 'GRUNWALD'
        ELSE 'STARE MIASTO'
    END AS DZIELNICA FROM ZESPOLY;

SELECT NAZWISKO, PLACA_POD, 
    CASE
        WHEN PLACA_POD > 480 THEN 'Powyżej 480'
        WHEN PLACA_POD = 480 THEN 'Dokładnie 480'
        ELSE 'Poniżej 480'
    END FROM PRACOWNICY;