SELECT MIN(PLACA_POD) AS MINIMUM, MAX(PLACA_POD) AS MAKSIMUM, MAX(PLACA_POD) - MIN(PLACA_POD) AS RÓŻNICA
    FROM PRACOWNICY;

SELECT ETAT, AVG(PLACA_POD) AS SREDNIA FROM PRACOWNICY
    GROUP BY ETAT
    ORDER BY SREDNIA DESC;

SELECT COUNT(*) AS PROFESOROWIE FROM PRACOWNICY
    WHERE ETAT = 'PROFESOR';

SELECT ID_ZESP, SUM(PLACA_POD) + SUM(PLACA_DOD) AS SUMARYCZNE_PLACE FROM PRACOWNICY
    GROUP BY ID_ZESP
    ORDER BY ID_ZESP;

SELECT MAX(SUM(PLACA_POD) + SUM(PLACA_DOD)) AS MAKS_SUM_PLACA FROM PRACOWNICY
    GROUP BY ID_ZESP;

SELECT ID_SZEFA, MIN(PLACA_POD) AS MINIMALNA FROM PRACOWNICY
    WHERE ID_SZEFA IS NOT NULL
    GROUP BY ID_SZEFA
    ORDER BY MINIMALNA DESC;

SELECT ID_ZESP, COUNT(*) AS ILU_PRACUJE FROM PRACOWNICY
    GROUP BY ID_ZESP
    ORDER BY ILU_PRACUJE DESC;

SELECT ID_ZESP, COUNT(*) AS ILU_PRACUJE FROM PRACOWNICY
    GROUP BY ID_ZESP HAVING COUNT(*) > 3
    ORDER BY ILU_PRACUJE DESC;

SELECT ID_PRAC FROM PRACOWNICY
    GROUP BY ID_PRAC HAVING COUNT(*) > 1;

SELECT ETAT, AVG(PLACA_POD) AS ŚREDNIA, COUNT(*) AS LICZBA FROM PRACOWNICY
    WHERE ZATRUDNIONY < DATE '1990-01-01'
    GROUP BY ETAT
    ORDER BY ETAT;

SELECT ID_ZESP, ETAT, ROUND(AVG(PLACA_POD + COALESCE(PLACA_DOD, 0)), 0) AS SREDNIA, ROUND(MAX(PLACA_POD + COALESCE(PLACA_DOD, 0)), 0) AS MAKSYMALNA FROM PRACOWNICY
    GROUP BY ETAT, ID_ZESP HAVING ETAT = 'ASYSTENT' OR ETAT = 'PROFESOR'
    ORDER BY ID_ZESP, ETAT;

SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS ILU_PRACOWNIKOW FROM PRACOWNICY
    GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
    ORDER BY ROK;

SELECT LENGTH(NAZWISKO) AS ILE_LITER, COUNT(*) AS W_ILU_NAZWISKACH FROM PRACOWNICY
    GROUP BY LENGTH(NAZWISKO)
    ORDER BY ILE_LITER;

SELECT COUNT(*) AS ILE_NAZWISK_Z_A FROM PRACOWNICY
    WHERE NAZWISKO LIKE '%A%';

SELECT 
    SUM(CASE
        WHEN INSTR(NAZWISKO, 'A', 1, 1) > 0 THEN 1
        ELSE 0
    END) AS ILE_NAZWISK_Z_A, 
    SUM(CASE
        WHEN INSTR(NAZWISKO, 'E', 1, 1) > 0 THEN 1
        ELSE 0
    END) AS ILE_NAZWISK_Z_E
    FROM PRACOWNICY;

SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC, 
    LISTAGG(NAZWISKO || ':' || PLACA_POD, ';')
    WITHIN GROUP (ORDER BY NAZWISKO) AS PRACOWNICY
    FROM PRACOWNICY GROUP BY ID_ZESP ORDER BY ID_ZESP;