SELECT NAZWISKO, ETAT, ID_ZESP, NAZWA 
    FROM PRACOWNICY INNER JOIN ZESPOLY USING(ID_ZESP)
    ORDER BY NAZWISKO;

SELECT NAZWISKO, ETAT, ID_ZESP, NAZWA 
    FROM PRACOWNICY INNER JOIN ZESPOLY USING(ID_ZESP)
    WHERE ADRES = 'PIOTROWO 3A'
    ORDER BY NAZWISKO;

SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX
    FROM PRACOWNICY JOIN ETATY ON PRACOWNICY.ETAT = ETATY.NAZWA
    ORDER BY ETAT, NAZWISKO;

SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX, 
    CASE
        WHEN PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX THEN 'OK'
        ELSE 'NIE'
    END AS CZY_PENSJA_OK
    FROM PRACOWNICY JOIN ETATY ON PRACOWNICY.ETAT = ETATY.NAZWA
    ORDER BY ETAT, NAZWISKO;

SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX
    FROM PRACOWNICY JOIN ETATY ON PRACOWNICY.ETAT = ETATY.NAZWA
    WHERE PLACA_POD NOT BETWEEN PLACA_MIN AND PLACA_MAX
    ORDER BY ETAT, NAZWISKO;

SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX
    FROM PRACOWNICY P JOIN ETATY E ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX
    ORDER BY NAZWISKO, KAT_PLAC;

SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX
    FROM PRACOWNICY P JOIN ETATY E ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX
    WHERE E.NAZWA = 'SEKRETARKA'
    ORDER BY NAZWISKO, KAT_PLAC;

SELECT P1.NAZWISKO AS PRACOWNIK, P1.ID_PRAC, P2.NAZWISKO AS SZEF, P1.ID_SZEFA
    FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P2.ID_PRAC = P1.ID_SZEFA
    ORDER BY P1.NAZWISKO;

SELECT P1.NAZWISKO AS PRACOWNIK, P1.ZATRUDNIONY AS PRAC_ZATRUDNIONY, P2.NAZWISKO AS SZEF, P2.ZATRUDNIONY AS SZEF_ZATRUDNIONY, EXTRACT(YEAR FROM (P1.ZATRUDNIONY - P2.ZATRUDNIONY) YEAR TO MONTH) AS LATA
    FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P2.ID_PRAC = P1.ID_SZEFA
    WHERE EXTRACT(YEAR FROM (P1.ZATRUDNIONY - P2.ZATRUDNIONY) YEAR TO MONTH) < 10
    ORDER BY P1.ZATRUDNIONY, P1.NAZWISKO;

SELECT Z.NAZWA, COUNT(*) AS LICZBA, AVG(P.PLACA_POD) AS SREDNIA_PLACA
    FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP)
    GROUP BY Z.NAZWA
    ORDER BY Z.NAZWA;

SELECT Z.NAZWA, 
    CASE
        WHEN COUNT(*) <= 2 THEN 'MAŁY'
        WHEN COUNT(*) <= 6 THEN 'ŚREDNI'
        ELSE 'DUŻY'
    END AS ETYKIETA
    FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP)
    GROUP BY Z.NAZWA
    ORDER BY Z.NAZWA;
