SELECT NAZWISKO, P.ID_ZESP, NAZWA
    FROM PRACOWNICY P LEFT JOIN ZESPOLY Z
        ON P.ID_ZESP = Z.ID_ZESP
    ORDER BY NAZWISKO;

SELECT NAZWA, Z.ID_ZESP,
    CASE
        WHEN P.NAZWISKO IS NULL THEN 'brak pracowników'
        ELSE P.NAZWISKO
    END FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z
        ON P.ID_ZESP = Z.ID_ZESP
    ORDER BY NAZWA, P.NAZWISKO;

SELECT
    CASE
        WHEN Z.NAZWA IS NULL THEN 'brak zespolu'
        ELSE Z.NAZWA
    END AS ZESPOL,
    CASE
        WHEN P.NAZWISKO IS NULL THEN 'brak pracowników'
        ELSE P.NAZWISKO
    END AS PRACOWNIK
    FROM ZESPOLY Z FULL JOIN PRACOWNICY P
        ON Z.ID_ZESP = P.ID_ZESP
    ORDER BY Z.NAZWA, P.NAZWISKO;

SELECT Z.NAZWA AS ZESPOL,
    CASE
        WHEN SUM(P.PLACA_POD) IS NULL THEN 0
        ELSE COUNT(*)
    END AS LICZBA, SUM(P.PLACA_POD) AS SUMA_PLAC
    FROM ZESPOLY Z LEFT JOIN PRACOWNICY P
        ON P.ID_ZESP = Z.ID_ZESP
    GROUP BY Z.NAZWA
    ORDER BY ZESPOL;

SELECT Z.NAZWA
    FROM ZESPOLY Z LEFT JOIN PRACOWNICY P
        ON P.ID_ZESP = Z.ID_ZESP
    GROUP BY Z.NAZWA HAVING SUM(P.PLACA_POD) IS NULL
    ORDER BY Z.NAZWA;

SELECT P1.NAZWISKO AS PRACOWNIK, P1.ID_PRAC, P2.NAZWISKO AS SZEF, P2.ID_PRAC AS ID_SZEFA
    FROM PRACOWNICY P1 LEFT JOIN PRACOWNICY P2
        ON P1.ID_SZEFA = P2.ID_PRAC
    ORDER BY P1.NAZWISKO;

SELECT P2.NAZWISKO AS PRACOWNIK, COUNT(distinct P1.ID_PRAC) AS LICZBA_PODWLADNYCH
    FROM PRACOWNICY P1 RIGHT JOIN PRACOWNICY P2
        ON P1.ID_SZEFA = P2.ID_PRAC
    GROUP BY P2.NAZWISKO
    ORDER BY PRACOWNIK;

SELECT P1.NAZWISKO, P1.ETAT, P1.PLACA_POD, Z.NAZWA, P2.NAZWISKO
    FROM PRACOWNICY P1 LEFT JOIN ZESPOLY Z
        ON P1.ID_ZESP = Z.ID_ZESP
    LEFT JOIN PRACOWNICY P2
        ON P1.ID_SZEFA = P2.ID_PRAC
    ORDER BY P1.NAZWISKO;

SELECT P1.NAZWISKO, Z.NAZWA
    FROM PRACOWNICY P1 CROSS JOIN ZESPOLY Z
    ORDER BY P1.NAZWISKO, Z.NAZWA;

SELECT COUNT(*)
    FROM ETATY, PRACOWNICY, ZESPOLY;

SELECT ETAT
    FROM PRACOWNICY P1
    WHERE EXTRACT(YEAR FROM P1.ZATRUDNIONY) = 1992
INTERSECT
SELECT ETAT
    FROM PRACOWNICY P2
    WHERE EXTRACT(YEAR FROM P2.ZATRUDNIONY) = 1993;

SELECT Z.ID_ZESP
    FROM ZESPOLY Z LEFT JOIN PRACOWNICY P
        ON Z.ID_ZESP = P.ID_ZESP
MINUS
SELECT Z2.ID_ZESP
    FROM ZESPOLY Z2 LEFT JOIN PRACOWNICY P2
        ON Z2.ID_ZESP = P2.ID_ZESP
    WHERE P2.NAZWISKO IS NOT NULL;

SELECT Z.ID_ZESP, Z.NAZWA
    FROM ZESPOLY Z LEFT JOIN PRACOWNICY P
        ON Z.ID_ZESP = P.ID_ZESP
MINUS
SELECT Z2.ID_ZESP, Z2.NAZWA
    FROM ZESPOLY Z2 LEFT JOIN PRACOWNICY P2
        ON Z2.ID_ZESP = P2.ID_ZESP
    WHERE P2.NAZWISKO IS NOT NULL;

SELECT NAZWISKO, PLACA_POD, 'Poniżej 480 złotych' AS PROG
    FROM PRACOWNICY
    WHERE PLACA_POD < 480
UNION
SELECT NAZWISKO, PLACA_POD, 'Dokładnie 480 złotych' AS PROG
    FROM PRACOWNICY
    WHERE PLACA_POD = 480
UNION
SELECT NAZWISKO, PLACA_POD, 'Powyżej 480 złotych' AS PROG
    FROM PRACOWNICY
    WHERE PLACA_POD > 480
    ORDER BY PLACA_POD;

