-- 1
SELECT Z.ID_ZESP, Z.NAZWA, Z.ADRES 
    FROM ZESPOLY Z
    WHERE NOT EXISTS (SELECT * FROM PRACOWNICY
        WHERE ID_ZESP = Z.ID_ZESP);

-- 2
SELECT P.NAZWISKO, P.PLACA_POD, P.ETAT FROM PRACOWNICY P
    WHERE P.PLACA_POD > (SELECT AVG(PLACA_POD) FROM PRACOWNICY
        GROUP BY ETAT HAVING ETAT = P.ETAT)
    ORDER BY P.PLACA_POD DESC;

-- 3
SELECT P.NAZWISKO, P.PLACA_POD FROM PRACOWNICY P
    WHERE EXISTS (SELECT * FROM PRACOWNICY 
        WHERE P.ID_SZEFA = PRACOWNICY.ID_PRAC AND P.PLACA_POD >= (0.75 * PRACOWNICY.PLACA_POD))
    ORDER BY P.NAZWISKO;

-- 4
SELECT NAZWISKO FROM PRACOWNICY
    WHERE ETAT = 'PROFESOR' AND ID_PRAC NOT IN (SELECT ID_SZEFA FROM PRACOWNICY P
        WHERE EXISTS (SELECT * FROM PRACOWNICY PR
            WHERE P.ETAT = 'STAZYSTA' AND PR.ID_PRAC = P.ID_SZEFA));
        
-- 5
SELECT Z.NAZWA, M.SUMA
    FROM (SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA FROM PRACOWNICY GROUP BY ID_ZESP) P
    JOIN (SELECT MAX(SUM(PLACA_POD)) AS SUMA FROM PRACOWNICY GROUP BY ID_ZESP) M
        ON P.SUMA = M.SUMA
    JOIN ZESPOLY Z
        ON P.ID_ZESP = Z.ID_ZESP;

-- 6
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY
    WHERE PLACA_POD >= (SELECT MAX(PLACA_POD) FROM PRACOWNICY);


SELECT NAZWISKO, PLACA_POD 
    FROM (SELECT * FROM PRACOWNICY P 
        WHERE PLACA_POD IN (SELECT MAX(PLACA_POD) FROM PRACOWNICY));

SELECT NAZWISKO, PLACA_POD
    FROM PRACOWNICY
    WHERE EXISTS (SELECT * FROM PRACOWNICY P 
        WHERE PLACA_POD IN (SELECT MAX(PLACA_POD) FROM PRACOWNICY));



SELECT * FROM ETATY;
SELECT * FROM PRACOWNICY;
SELECT * FROM ZESPOLY;
