-- 1
SELECT NAZWISKO, PLACA_POD
    FROM PRACOWNICY FETCH FIRST 3 ROWS ONLY;

SELECT NAZWISKO, PLACA_POD
    FROM PRACOWNICY
    WHERE ROWNUM <= 3;

-- 2
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY
    ORDER BY PLACA_POD DESC
    OFFSET 5 ROWS
    FETCH NEXT 5 ROWS ONLY;

SELECT P.NAZWISKO, P.PLACA_POD
    FROM (SELECT ROWNUM AS RZAD, NAZWISKO, PLACA_POD FROM (SELECT * FROM PRACOWNICY ORDER BY PLACA_POD DESC)) P
    WHERE P.RZAD BETWEEN 6 AND 10;

-- 3
WITH TABELA(NAZWISKO, PLACA_POD, SREDNIA) AS
    (SELECT NAZWISKO, PLACA_POD, PLACA_POD - (SELECT AVG(PLACA_POD) FROM PRACOWNICY P2 GROUP BY P2.ID_ZESP HAVING P1.ID_ZESP = P2.ID_ZESP) FROM PRACOWNICY P1)
SELECT * FROM TABELA
    WHERE SREDNIA > 0
    ORDER BY NAZWISKO;

-- 4
WITH LATA(ROK, LICZBA) AS
    (SELECT EXTRACT(YEAR FROM ZATRUDNIONY), COUNT(*) FROM PRACOWNICY GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY))
SELECT * FROM LATA
    ORDER BY LICZBA DESC;

-- 5
WITH LATA(ROK, LICZBA) AS
    (SELECT EXTRACT(YEAR FROM ZATRUDNIONY), COUNT(*) FROM PRACOWNICY GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY))
SELECT * FROM LATA
    ORDER BY LICZBA DESC
    FETCH FIRST 1 ROWS ONLY;

-- 6
WITH ASYSTENCI(NAZWISKO, ETAT, ID_ZESP) AS
    (SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE ETAT = 'ASYSTENT'),
    PIOTROWO(ID_ZESP, ADRES, NAZWA) AS
    (SELECT ID_ZESP, ADRES, NAZWA FROM ZESPOLY WHERE ADRES = 'PIOTROWO 3A')
SELECT NAZWISKO, ETAT, NAZWA, ADRES 
    FROM ASYSTENCI JOIN PIOTROWO ON ASYSTENCI.ID_ZESP = PIOTROWO.ID_ZESP;

-- 7
WITH PLACA(ID_ZESP, PLACA) AS
    (SELECT ID_ZESP, SUM(PLACA_POD) FROM PRACOWNICY GROUP BY ID_ZESP),
    ZESP(ID_ZESP, NAZWA) AS
    (SELECT ID_ZESP, NAZWA FROM ZESPOLY)
SELECT NAZWA, PLACA AS MAKS_SUMA_PLAC
    FROM PLACA JOIN ZESP ON PLACA.ID_ZESP = ZESP.ID_ZESP
    ORDER BY PLACA DESC
    FETCH FIRST 1 ROWS ONLY;

-- 8
WITH PODWLADNI(ID_PRAC, ID_SZEFA, NAZWISKO, POZIOM) AS
    (SELECT ID_PRAC, ID_SZEFA, NAZWISKO, 1
        FROM PRACOWNICY
        WHERE NAZWISKO = 'BRZEZINSKI'
    UNION ALL
    SELECT S.ID_PRAC, S.ID_SZEFA, S.NAZWISKO, POZIOM + 1
    FROM PRACOWNICY S JOIN PODWLADNI P
        ON P.ID_PRAC = S.ID_SZEFA)
SELECT NAZWISKO, POZIOM AS POZYCJA_W_HIERARCHII FROM PODWLADNI
    ORDER BY POZIOM, NAZWISKO;

WITH PODWLADNI(ID_PRAC, ID_SZEFA, NAZWISKO, POZIOM) AS
    (SELECT ID_PRAC, ID_SZEFA, NAZWISKO, 1
        FROM PRACOWNICY
        WHERE NAZWISKO = 'BRZEZINSKI'
    UNION ALL
    SELECT P.ID_PRAC, P.ID_SZEFA, P.NAZWISKO, POZIOM + 1
        FROM PODWLADNI S JOIN PRACOWNICY P ON S.ID_PRAC = P.ID_SZEFA)
    SEARCH DEPTH FIRST BY NAZWISKO SET PORZADEK_POTOMKOW
SELECT NAZWISKO, POZIOM AS POZYCJA_W_HIERARCHII
    FROM PODWLADNI
    ORDER BY PORZADEK_POTOMKOW, NAZWISKO;

-- 9
WITH PODWLADNI(ID_PRAC, ID_SZEFA, NAZWISKO, POZIOM) AS
    (SELECT ID_PRAC, ID_SZEFA, NAZWISKO, 1
        FROM PRACOWNICY
        WHERE NAZWISKO = 'BRZEZINSKI'
    UNION ALL
    SELECT S.ID_PRAC, S.ID_SZEFA, S.NAZWISKO, POZIOM + 1
    FROM PRACOWNICY S JOIN PODWLADNI P
        ON P.ID_PRAC = S.ID_SZEFA)
SELECT LPAD(NAZWISKO, LENGTH(NAZWISKO) + POZIOM - 1, '-') AS NAZWISKO, POZIOM AS POZYCJA_W_HIERARCHII FROM PODWLADNI
    ORDER BY POZIOM, NAZWISKO;

WITH PODWLADNI(ID_PRAC, ID_SZEFA, NAZWISKO, POZIOM) AS
    (SELECT ID_PRAC, ID_SZEFA, NAZWISKO, 1
        FROM PRACOWNICY
        WHERE NAZWISKO = 'BRZEZINSKI'
    UNION ALL
    SELECT P.ID_PRAC, P.ID_SZEFA, P.NAZWISKO, POZIOM + 1
        FROM PODWLADNI S JOIN PRACOWNICY P ON S.ID_PRAC = P.ID_SZEFA)
    SEARCH DEPTH FIRST BY NAZWISKO SET PORZADEK_POTOMKOW
SELECT LPAD(NAZWISKO, LENGTH(NAZWISKO) + POZIOM - 1, '-') AS NAZWISKO, POZIOM AS POZYCJA_W_HIERARCHII
    FROM PODWLADNI
    ORDER BY PORZADEK_POTOMKOW, NAZWISKO;

